//AUTOGENERATED FILE - Do not modify directly
//Change the .tt file instead

namespace Konamiman.NestorMSX.Z80Debugger
{
    public partial class InstructionExtractor
    {
        private readonly Z80Instruction[] cbInstructionPrototypes =
        {
            new Z80Instruction //0xCB 0x00
            {
                FormatString = "rlc b",
				RawBytes = new byte[] { 0xCB, 0x00 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x01
            {
                FormatString = "rlc c",
				RawBytes = new byte[] { 0xCB, 0x01 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x02
            {
                FormatString = "rlc d",
				RawBytes = new byte[] { 0xCB, 0x02 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x03
            {
                FormatString = "rlc e",
				RawBytes = new byte[] { 0xCB, 0x03 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x04
            {
                FormatString = "rlc h",
				RawBytes = new byte[] { 0xCB, 0x04 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x05
            {
                FormatString = "rlc l",
				RawBytes = new byte[] { 0xCB, 0x05 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x06
            {
                FormatString = "rlc (hl)",
				RawBytes = new byte[] { 0xCB, 0x06 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x07
            {
                FormatString = "rlc a",
				RawBytes = new byte[] { 0xCB, 0x07 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x08
            {
                FormatString = "rrc b",
				RawBytes = new byte[] { 0xCB, 0x08 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x09
            {
                FormatString = "rrc c",
				RawBytes = new byte[] { 0xCB, 0x09 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x0A
            {
                FormatString = "rrc d",
				RawBytes = new byte[] { 0xCB, 0x0A },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x0B
            {
                FormatString = "rrc e",
				RawBytes = new byte[] { 0xCB, 0x0B },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x0C
            {
                FormatString = "rrc h",
				RawBytes = new byte[] { 0xCB, 0x0C },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x0D
            {
                FormatString = "rrc l",
				RawBytes = new byte[] { 0xCB, 0x0D },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x0E
            {
                FormatString = "rrc (hl)",
				RawBytes = new byte[] { 0xCB, 0x0E },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x0F
            {
                FormatString = "rrc a",
				RawBytes = new byte[] { 0xCB, 0x0F },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x10
            {
                FormatString = "rl b",
				RawBytes = new byte[] { 0xCB, 0x10 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x11
            {
                FormatString = "rl c",
				RawBytes = new byte[] { 0xCB, 0x11 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x12
            {
                FormatString = "rl d",
				RawBytes = new byte[] { 0xCB, 0x12 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x13
            {
                FormatString = "rl e",
				RawBytes = new byte[] { 0xCB, 0x13 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x14
            {
                FormatString = "rl h",
				RawBytes = new byte[] { 0xCB, 0x14 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x15
            {
                FormatString = "rl l",
				RawBytes = new byte[] { 0xCB, 0x15 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x16
            {
                FormatString = "rl (hl)",
				RawBytes = new byte[] { 0xCB, 0x16 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x17
            {
                FormatString = "rl a",
				RawBytes = new byte[] { 0xCB, 0x17 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x18
            {
                FormatString = "rr b",
				RawBytes = new byte[] { 0xCB, 0x18 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x19
            {
                FormatString = "rr c",
				RawBytes = new byte[] { 0xCB, 0x19 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x1A
            {
                FormatString = "rr d",
				RawBytes = new byte[] { 0xCB, 0x1A },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x1B
            {
                FormatString = "rr e",
				RawBytes = new byte[] { 0xCB, 0x1B },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x1C
            {
                FormatString = "rr h",
				RawBytes = new byte[] { 0xCB, 0x1C },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x1D
            {
                FormatString = "rr l",
				RawBytes = new byte[] { 0xCB, 0x1D },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x1E
            {
                FormatString = "rr (hl)",
				RawBytes = new byte[] { 0xCB, 0x1E },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x1F
            {
                FormatString = "rr a",
				RawBytes = new byte[] { 0xCB, 0x1F },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x20
            {
                FormatString = "sla b",
				RawBytes = new byte[] { 0xCB, 0x20 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x21
            {
                FormatString = "sla c",
				RawBytes = new byte[] { 0xCB, 0x21 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x22
            {
                FormatString = "sla d",
				RawBytes = new byte[] { 0xCB, 0x22 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x23
            {
                FormatString = "sla e",
				RawBytes = new byte[] { 0xCB, 0x23 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x24
            {
                FormatString = "sla h",
				RawBytes = new byte[] { 0xCB, 0x24 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x25
            {
                FormatString = "sla l",
				RawBytes = new byte[] { 0xCB, 0x25 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x26
            {
                FormatString = "sla (hl)",
				RawBytes = new byte[] { 0xCB, 0x26 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x27
            {
                FormatString = "sla a",
				RawBytes = new byte[] { 0xCB, 0x27 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x28
            {
                FormatString = "sra b",
				RawBytes = new byte[] { 0xCB, 0x28 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x29
            {
                FormatString = "sra c",
				RawBytes = new byte[] { 0xCB, 0x29 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x2A
            {
                FormatString = "sra d",
				RawBytes = new byte[] { 0xCB, 0x2A },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x2B
            {
                FormatString = "sra e",
				RawBytes = new byte[] { 0xCB, 0x2B },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x2C
            {
                FormatString = "sra h",
				RawBytes = new byte[] { 0xCB, 0x2C },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x2D
            {
                FormatString = "sra l",
				RawBytes = new byte[] { 0xCB, 0x2D },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x2E
            {
                FormatString = "sra (hl)",
				RawBytes = new byte[] { 0xCB, 0x2E },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x2F
            {
                FormatString = "sra a",
				RawBytes = new byte[] { 0xCB, 0x2F },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x30
            {
                FormatString = "sll b",
				RawBytes = new byte[] { 0xCB, 0x30 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Undocumented,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x31
            {
                FormatString = "sll c",
				RawBytes = new byte[] { 0xCB, 0x31 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Undocumented,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x32
            {
                FormatString = "sll d",
				RawBytes = new byte[] { 0xCB, 0x32 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Undocumented,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x33
            {
                FormatString = "sll e",
				RawBytes = new byte[] { 0xCB, 0x33 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Undocumented,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x34
            {
                FormatString = "sll h",
				RawBytes = new byte[] { 0xCB, 0x34 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Undocumented,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x35
            {
                FormatString = "sll l",
				RawBytes = new byte[] { 0xCB, 0x35 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Undocumented,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x36
            {
                FormatString = "sll (hl)",
				RawBytes = new byte[] { 0xCB, 0x36 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Undocumented,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x37
            {
                FormatString = "sll a",
				RawBytes = new byte[] { 0xCB, 0x37 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Undocumented,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x38
            {
                FormatString = "srl b",
				RawBytes = new byte[] { 0xCB, 0x38 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x39
            {
                FormatString = "srl c",
				RawBytes = new byte[] { 0xCB, 0x39 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x3A
            {
                FormatString = "srl d",
				RawBytes = new byte[] { 0xCB, 0x3A },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x3B
            {
                FormatString = "srl e",
				RawBytes = new byte[] { 0xCB, 0x3B },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x3C
            {
                FormatString = "srl h",
				RawBytes = new byte[] { 0xCB, 0x3C },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x3D
            {
                FormatString = "srl l",
				RawBytes = new byte[] { 0xCB, 0x3D },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x3E
            {
                FormatString = "srl (hl)",
				RawBytes = new byte[] { 0xCB, 0x3E },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x3F
            {
                FormatString = "srl a",
				RawBytes = new byte[] { 0xCB, 0x3F },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x40
            {
                FormatString = "bit 0,b",
				RawBytes = new byte[] { 0xCB, 0x40 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x41
            {
                FormatString = "bit 0,c",
				RawBytes = new byte[] { 0xCB, 0x41 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x42
            {
                FormatString = "bit 0,d",
				RawBytes = new byte[] { 0xCB, 0x42 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x43
            {
                FormatString = "bit 0,e",
				RawBytes = new byte[] { 0xCB, 0x43 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x44
            {
                FormatString = "bit 0,h",
				RawBytes = new byte[] { 0xCB, 0x44 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x45
            {
                FormatString = "bit 0,l",
				RawBytes = new byte[] { 0xCB, 0x45 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x46
            {
                FormatString = "bit 0,(hl)",
				RawBytes = new byte[] { 0xCB, 0x46 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x47
            {
                FormatString = "bit 0,a",
				RawBytes = new byte[] { 0xCB, 0x47 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x48
            {
                FormatString = "bit 1,b",
				RawBytes = new byte[] { 0xCB, 0x48 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x49
            {
                FormatString = "bit 1,c",
				RawBytes = new byte[] { 0xCB, 0x49 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x4A
            {
                FormatString = "bit 1,d",
				RawBytes = new byte[] { 0xCB, 0x4A },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x4B
            {
                FormatString = "bit 1,e",
				RawBytes = new byte[] { 0xCB, 0x4B },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x4C
            {
                FormatString = "bit 1,h",
				RawBytes = new byte[] { 0xCB, 0x4C },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x4D
            {
                FormatString = "bit 1,l",
				RawBytes = new byte[] { 0xCB, 0x4D },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x4E
            {
                FormatString = "bit 1,(hl)",
				RawBytes = new byte[] { 0xCB, 0x4E },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x4F
            {
                FormatString = "bit 1,a",
				RawBytes = new byte[] { 0xCB, 0x4F },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x50
            {
                FormatString = "bit 2,b",
				RawBytes = new byte[] { 0xCB, 0x50 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x51
            {
                FormatString = "bit 2,c",
				RawBytes = new byte[] { 0xCB, 0x51 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x52
            {
                FormatString = "bit 2,d",
				RawBytes = new byte[] { 0xCB, 0x52 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x53
            {
                FormatString = "bit 2,e",
				RawBytes = new byte[] { 0xCB, 0x53 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x54
            {
                FormatString = "bit 2,h",
				RawBytes = new byte[] { 0xCB, 0x54 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x55
            {
                FormatString = "bit 2,l",
				RawBytes = new byte[] { 0xCB, 0x55 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x56
            {
                FormatString = "bit 2,(hl)",
				RawBytes = new byte[] { 0xCB, 0x56 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x57
            {
                FormatString = "bit 2,a",
				RawBytes = new byte[] { 0xCB, 0x57 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x58
            {
                FormatString = "bit 3,b",
				RawBytes = new byte[] { 0xCB, 0x58 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x59
            {
                FormatString = "bit 3,c",
				RawBytes = new byte[] { 0xCB, 0x59 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x5A
            {
                FormatString = "bit 3,d",
				RawBytes = new byte[] { 0xCB, 0x5A },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x5B
            {
                FormatString = "bit 3,e",
				RawBytes = new byte[] { 0xCB, 0x5B },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x5C
            {
                FormatString = "bit 3,h",
				RawBytes = new byte[] { 0xCB, 0x5C },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x5D
            {
                FormatString = "bit 3,l",
				RawBytes = new byte[] { 0xCB, 0x5D },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x5E
            {
                FormatString = "bit 3,(hl)",
				RawBytes = new byte[] { 0xCB, 0x5E },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x5F
            {
                FormatString = "bit 3,a",
				RawBytes = new byte[] { 0xCB, 0x5F },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x60
            {
                FormatString = "bit 4,b",
				RawBytes = new byte[] { 0xCB, 0x60 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x61
            {
                FormatString = "bit 4,c",
				RawBytes = new byte[] { 0xCB, 0x61 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x62
            {
                FormatString = "bit 4,d",
				RawBytes = new byte[] { 0xCB, 0x62 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x63
            {
                FormatString = "bit 4,e",
				RawBytes = new byte[] { 0xCB, 0x63 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x64
            {
                FormatString = "bit 4,h",
				RawBytes = new byte[] { 0xCB, 0x64 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x65
            {
                FormatString = "bit 4,l",
				RawBytes = new byte[] { 0xCB, 0x65 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x66
            {
                FormatString = "bit 4,(hl)",
				RawBytes = new byte[] { 0xCB, 0x66 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x67
            {
                FormatString = "bit 4,a",
				RawBytes = new byte[] { 0xCB, 0x67 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x68
            {
                FormatString = "bit 5,b",
				RawBytes = new byte[] { 0xCB, 0x68 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x69
            {
                FormatString = "bit 5,c",
				RawBytes = new byte[] { 0xCB, 0x69 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x6A
            {
                FormatString = "bit 5,d",
				RawBytes = new byte[] { 0xCB, 0x6A },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x6B
            {
                FormatString = "bit 5,e",
				RawBytes = new byte[] { 0xCB, 0x6B },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x6C
            {
                FormatString = "bit 5,h",
				RawBytes = new byte[] { 0xCB, 0x6C },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x6D
            {
                FormatString = "bit 5,l",
				RawBytes = new byte[] { 0xCB, 0x6D },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x6E
            {
                FormatString = "bit 5,(hl)",
				RawBytes = new byte[] { 0xCB, 0x6E },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x6F
            {
                FormatString = "bit 5,a",
				RawBytes = new byte[] { 0xCB, 0x6F },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x70
            {
                FormatString = "bit 6,b",
				RawBytes = new byte[] { 0xCB, 0x70 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x71
            {
                FormatString = "bit 6,c",
				RawBytes = new byte[] { 0xCB, 0x71 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x72
            {
                FormatString = "bit 6,d",
				RawBytes = new byte[] { 0xCB, 0x72 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x73
            {
                FormatString = "bit 6,e",
				RawBytes = new byte[] { 0xCB, 0x73 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x74
            {
                FormatString = "bit 6,h",
				RawBytes = new byte[] { 0xCB, 0x74 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x75
            {
                FormatString = "bit 6,l",
				RawBytes = new byte[] { 0xCB, 0x75 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x76
            {
                FormatString = "bit 6,(hl)",
				RawBytes = new byte[] { 0xCB, 0x76 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x77
            {
                FormatString = "bit 6,a",
				RawBytes = new byte[] { 0xCB, 0x77 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x78
            {
                FormatString = "bit 7,b",
				RawBytes = new byte[] { 0xCB, 0x78 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x79
            {
                FormatString = "bit 7,c",
				RawBytes = new byte[] { 0xCB, 0x79 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x7A
            {
                FormatString = "bit 7,d",
				RawBytes = new byte[] { 0xCB, 0x7A },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x7B
            {
                FormatString = "bit 7,e",
				RawBytes = new byte[] { 0xCB, 0x7B },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x7C
            {
                FormatString = "bit 7,h",
				RawBytes = new byte[] { 0xCB, 0x7C },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x7D
            {
                FormatString = "bit 7,l",
				RawBytes = new byte[] { 0xCB, 0x7D },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x7E
            {
                FormatString = "bit 7,(hl)",
				RawBytes = new byte[] { 0xCB, 0x7E },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x7F
            {
                FormatString = "bit 7,a",
				RawBytes = new byte[] { 0xCB, 0x7F },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x80
            {
                FormatString = "res 0,b",
				RawBytes = new byte[] { 0xCB, 0x80 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x81
            {
                FormatString = "res 0,c",
				RawBytes = new byte[] { 0xCB, 0x81 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x82
            {
                FormatString = "res 0,d",
				RawBytes = new byte[] { 0xCB, 0x82 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x83
            {
                FormatString = "res 0,e",
				RawBytes = new byte[] { 0xCB, 0x83 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x84
            {
                FormatString = "res 0,h",
				RawBytes = new byte[] { 0xCB, 0x84 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x85
            {
                FormatString = "res 0,l",
				RawBytes = new byte[] { 0xCB, 0x85 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x86
            {
                FormatString = "res 0,(hl)",
				RawBytes = new byte[] { 0xCB, 0x86 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x87
            {
                FormatString = "res 0,a",
				RawBytes = new byte[] { 0xCB, 0x87 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x88
            {
                FormatString = "res 1,b",
				RawBytes = new byte[] { 0xCB, 0x88 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x89
            {
                FormatString = "res 1,c",
				RawBytes = new byte[] { 0xCB, 0x89 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x8A
            {
                FormatString = "res 1,d",
				RawBytes = new byte[] { 0xCB, 0x8A },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x8B
            {
                FormatString = "res 1,e",
				RawBytes = new byte[] { 0xCB, 0x8B },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x8C
            {
                FormatString = "res 1,h",
				RawBytes = new byte[] { 0xCB, 0x8C },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x8D
            {
                FormatString = "res 1,l",
				RawBytes = new byte[] { 0xCB, 0x8D },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x8E
            {
                FormatString = "res 1,(hl)",
				RawBytes = new byte[] { 0xCB, 0x8E },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x8F
            {
                FormatString = "res 1,a",
				RawBytes = new byte[] { 0xCB, 0x8F },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x90
            {
                FormatString = "res 2,b",
				RawBytes = new byte[] { 0xCB, 0x90 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x91
            {
                FormatString = "res 2,c",
				RawBytes = new byte[] { 0xCB, 0x91 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x92
            {
                FormatString = "res 2,d",
				RawBytes = new byte[] { 0xCB, 0x92 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x93
            {
                FormatString = "res 2,e",
				RawBytes = new byte[] { 0xCB, 0x93 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x94
            {
                FormatString = "res 2,h",
				RawBytes = new byte[] { 0xCB, 0x94 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x95
            {
                FormatString = "res 2,l",
				RawBytes = new byte[] { 0xCB, 0x95 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x96
            {
                FormatString = "res 2,(hl)",
				RawBytes = new byte[] { 0xCB, 0x96 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x97
            {
                FormatString = "res 2,a",
				RawBytes = new byte[] { 0xCB, 0x97 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x98
            {
                FormatString = "res 3,b",
				RawBytes = new byte[] { 0xCB, 0x98 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x99
            {
                FormatString = "res 3,c",
				RawBytes = new byte[] { 0xCB, 0x99 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x9A
            {
                FormatString = "res 3,d",
				RawBytes = new byte[] { 0xCB, 0x9A },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x9B
            {
                FormatString = "res 3,e",
				RawBytes = new byte[] { 0xCB, 0x9B },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x9C
            {
                FormatString = "res 3,h",
				RawBytes = new byte[] { 0xCB, 0x9C },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x9D
            {
                FormatString = "res 3,l",
				RawBytes = new byte[] { 0xCB, 0x9D },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x9E
            {
                FormatString = "res 3,(hl)",
				RawBytes = new byte[] { 0xCB, 0x9E },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0x9F
            {
                FormatString = "res 3,a",
				RawBytes = new byte[] { 0xCB, 0x9F },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xA0
            {
                FormatString = "res 4,b",
				RawBytes = new byte[] { 0xCB, 0xA0 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xA1
            {
                FormatString = "res 4,c",
				RawBytes = new byte[] { 0xCB, 0xA1 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xA2
            {
                FormatString = "res 4,d",
				RawBytes = new byte[] { 0xCB, 0xA2 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xA3
            {
                FormatString = "res 4,e",
				RawBytes = new byte[] { 0xCB, 0xA3 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xA4
            {
                FormatString = "res 4,h",
				RawBytes = new byte[] { 0xCB, 0xA4 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xA5
            {
                FormatString = "res 4,l",
				RawBytes = new byte[] { 0xCB, 0xA5 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xA6
            {
                FormatString = "res 4,(hl)",
				RawBytes = new byte[] { 0xCB, 0xA6 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xA7
            {
                FormatString = "res 4,a",
				RawBytes = new byte[] { 0xCB, 0xA7 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xA8
            {
                FormatString = "res 5,b",
				RawBytes = new byte[] { 0xCB, 0xA8 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xA9
            {
                FormatString = "res 5,c",
				RawBytes = new byte[] { 0xCB, 0xA9 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xAA
            {
                FormatString = "res 5,d",
				RawBytes = new byte[] { 0xCB, 0xAA },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xAB
            {
                FormatString = "res 5,e",
				RawBytes = new byte[] { 0xCB, 0xAB },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xAC
            {
                FormatString = "res 5,h",
				RawBytes = new byte[] { 0xCB, 0xAC },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xAD
            {
                FormatString = "res 5,l",
				RawBytes = new byte[] { 0xCB, 0xAD },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xAE
            {
                FormatString = "res 5,(hl)",
				RawBytes = new byte[] { 0xCB, 0xAE },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xAF
            {
                FormatString = "res 5,a",
				RawBytes = new byte[] { 0xCB, 0xAF },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xB0
            {
                FormatString = "res 6,b",
				RawBytes = new byte[] { 0xCB, 0xB0 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xB1
            {
                FormatString = "res 6,c",
				RawBytes = new byte[] { 0xCB, 0xB1 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xB2
            {
                FormatString = "res 6,d",
				RawBytes = new byte[] { 0xCB, 0xB2 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xB3
            {
                FormatString = "res 6,e",
				RawBytes = new byte[] { 0xCB, 0xB3 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xB4
            {
                FormatString = "res 6,h",
				RawBytes = new byte[] { 0xCB, 0xB4 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xB5
            {
                FormatString = "res 6,l",
				RawBytes = new byte[] { 0xCB, 0xB5 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xB6
            {
                FormatString = "res 6,(hl)",
				RawBytes = new byte[] { 0xCB, 0xB6 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xB7
            {
                FormatString = "res 6,a",
				RawBytes = new byte[] { 0xCB, 0xB7 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xB8
            {
                FormatString = "res 7,b",
				RawBytes = new byte[] { 0xCB, 0xB8 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xB9
            {
                FormatString = "res 7,c",
				RawBytes = new byte[] { 0xCB, 0xB9 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xBA
            {
                FormatString = "res 7,d",
				RawBytes = new byte[] { 0xCB, 0xBA },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xBB
            {
                FormatString = "res 7,e",
				RawBytes = new byte[] { 0xCB, 0xBB },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xBC
            {
                FormatString = "res 7,h",
				RawBytes = new byte[] { 0xCB, 0xBC },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xBD
            {
                FormatString = "res 7,l",
				RawBytes = new byte[] { 0xCB, 0xBD },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xBE
            {
                FormatString = "res 7,(hl)",
				RawBytes = new byte[] { 0xCB, 0xBE },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xBF
            {
                FormatString = "res 7,a",
				RawBytes = new byte[] { 0xCB, 0xBF },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xC0
            {
                FormatString = "set 0,b",
				RawBytes = new byte[] { 0xCB, 0xC0 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xC1
            {
                FormatString = "set 0,c",
				RawBytes = new byte[] { 0xCB, 0xC1 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xC2
            {
                FormatString = "set 0,d",
				RawBytes = new byte[] { 0xCB, 0xC2 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xC3
            {
                FormatString = "set 0,e",
				RawBytes = new byte[] { 0xCB, 0xC3 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xC4
            {
                FormatString = "set 0,h",
				RawBytes = new byte[] { 0xCB, 0xC4 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xC5
            {
                FormatString = "set 0,l",
				RawBytes = new byte[] { 0xCB, 0xC5 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xC6
            {
                FormatString = "set 0,(hl)",
				RawBytes = new byte[] { 0xCB, 0xC6 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xC7
            {
                FormatString = "set 0,a",
				RawBytes = new byte[] { 0xCB, 0xC7 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xC8
            {
                FormatString = "set 1,b",
				RawBytes = new byte[] { 0xCB, 0xC8 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xC9
            {
                FormatString = "set 1,c",
				RawBytes = new byte[] { 0xCB, 0xC9 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xCA
            {
                FormatString = "set 1,d",
				RawBytes = new byte[] { 0xCB, 0xCA },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xCB
            {
                FormatString = "set 1,e",
				RawBytes = new byte[] { 0xCB, 0xCB },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xCC
            {
                FormatString = "set 1,h",
				RawBytes = new byte[] { 0xCB, 0xCC },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xCD
            {
                FormatString = "set 1,l",
				RawBytes = new byte[] { 0xCB, 0xCD },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xCE
            {
                FormatString = "set 1,(hl)",
				RawBytes = new byte[] { 0xCB, 0xCE },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xCF
            {
                FormatString = "set 1,a",
				RawBytes = new byte[] { 0xCB, 0xCF },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xD0
            {
                FormatString = "set 2,b",
				RawBytes = new byte[] { 0xCB, 0xD0 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xD1
            {
                FormatString = "set 2,c",
				RawBytes = new byte[] { 0xCB, 0xD1 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xD2
            {
                FormatString = "set 2,d",
				RawBytes = new byte[] { 0xCB, 0xD2 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xD3
            {
                FormatString = "set 2,e",
				RawBytes = new byte[] { 0xCB, 0xD3 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xD4
            {
                FormatString = "set 2,h",
				RawBytes = new byte[] { 0xCB, 0xD4 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xD5
            {
                FormatString = "set 2,l",
				RawBytes = new byte[] { 0xCB, 0xD5 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xD6
            {
                FormatString = "set 2,(hl)",
				RawBytes = new byte[] { 0xCB, 0xD6 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xD7
            {
                FormatString = "set 2,a",
				RawBytes = new byte[] { 0xCB, 0xD7 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xD8
            {
                FormatString = "set 3,b",
				RawBytes = new byte[] { 0xCB, 0xD8 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xD9
            {
                FormatString = "set 3,c",
				RawBytes = new byte[] { 0xCB, 0xD9 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xDA
            {
                FormatString = "set 3,d",
				RawBytes = new byte[] { 0xCB, 0xDA },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xDB
            {
                FormatString = "set 3,e",
				RawBytes = new byte[] { 0xCB, 0xDB },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xDC
            {
                FormatString = "set 3,h",
				RawBytes = new byte[] { 0xCB, 0xDC },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xDD
            {
                FormatString = "set 3,l",
				RawBytes = new byte[] { 0xCB, 0xDD },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xDE
            {
                FormatString = "set 3,(hl)",
				RawBytes = new byte[] { 0xCB, 0xDE },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xDF
            {
                FormatString = "set 3,a",
				RawBytes = new byte[] { 0xCB, 0xDF },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xE0
            {
                FormatString = "set 4,b",
				RawBytes = new byte[] { 0xCB, 0xE0 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xE1
            {
                FormatString = "set 4,c",
				RawBytes = new byte[] { 0xCB, 0xE1 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xE2
            {
                FormatString = "set 4,d",
				RawBytes = new byte[] { 0xCB, 0xE2 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xE3
            {
                FormatString = "set 4,e",
				RawBytes = new byte[] { 0xCB, 0xE3 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xE4
            {
                FormatString = "set 4,h",
				RawBytes = new byte[] { 0xCB, 0xE4 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xE5
            {
                FormatString = "set 4,l",
				RawBytes = new byte[] { 0xCB, 0xE5 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xE6
            {
                FormatString = "set 4,(hl)",
				RawBytes = new byte[] { 0xCB, 0xE6 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xE7
            {
                FormatString = "set 4,a",
				RawBytes = new byte[] { 0xCB, 0xE7 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xE8
            {
                FormatString = "set 5,b",
				RawBytes = new byte[] { 0xCB, 0xE8 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xE9
            {
                FormatString = "set 5,c",
				RawBytes = new byte[] { 0xCB, 0xE9 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xEA
            {
                FormatString = "set 5,d",
				RawBytes = new byte[] { 0xCB, 0xEA },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xEB
            {
                FormatString = "set 5,e",
				RawBytes = new byte[] { 0xCB, 0xEB },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xEC
            {
                FormatString = "set 5,h",
				RawBytes = new byte[] { 0xCB, 0xEC },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xED
            {
                FormatString = "set 5,l",
				RawBytes = new byte[] { 0xCB, 0xED },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xEE
            {
                FormatString = "set 5,(hl)",
				RawBytes = new byte[] { 0xCB, 0xEE },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xEF
            {
                FormatString = "set 5,a",
				RawBytes = new byte[] { 0xCB, 0xEF },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xF0
            {
                FormatString = "set 6,b",
				RawBytes = new byte[] { 0xCB, 0xF0 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xF1
            {
                FormatString = "set 6,c",
				RawBytes = new byte[] { 0xCB, 0xF1 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xF2
            {
                FormatString = "set 6,d",
				RawBytes = new byte[] { 0xCB, 0xF2 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xF3
            {
                FormatString = "set 6,e",
				RawBytes = new byte[] { 0xCB, 0xF3 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xF4
            {
                FormatString = "set 6,h",
				RawBytes = new byte[] { 0xCB, 0xF4 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xF5
            {
                FormatString = "set 6,l",
				RawBytes = new byte[] { 0xCB, 0xF5 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xF6
            {
                FormatString = "set 6,(hl)",
				RawBytes = new byte[] { 0xCB, 0xF6 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xF7
            {
                FormatString = "set 6,a",
				RawBytes = new byte[] { 0xCB, 0xF7 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xF8
            {
                FormatString = "set 7,b",
				RawBytes = new byte[] { 0xCB, 0xF8 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xF9
            {
                FormatString = "set 7,c",
				RawBytes = new byte[] { 0xCB, 0xF9 },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xFA
            {
                FormatString = "set 7,d",
				RawBytes = new byte[] { 0xCB, 0xFA },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xFB
            {
                FormatString = "set 7,e",
				RawBytes = new byte[] { 0xCB, 0xFB },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xFC
            {
                FormatString = "set 7,h",
				RawBytes = new byte[] { 0xCB, 0xFC },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xFD
            {
                FormatString = "set 7,l",
				RawBytes = new byte[] { 0xCB, 0xFD },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xFE
            {
                FormatString = "set 7,(hl)",
				RawBytes = new byte[] { 0xCB, 0xFE },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = true,
                WritesToPort = false
            },
            new Z80Instruction //0xCB 0xFF
            {
                FormatString = "set 7,a",
				RawBytes = new byte[] { 0xCB, 0xFF },
				Operands = new Operand[0],
				InstructionType = InstructionType.Standard,
				ChangesSp = false,
                ChangesPc = false,
                WritesToMemory = false,
                WritesToPort = false
            },
		};
    }
}